# Generated by Django 5.0.3 on 2024-04-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_delete_blog_details_delete_blogs_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
