# Generated by Django 5.0.3 on 2024-04-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blogpost_title_commentmodelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodelform',
            name='comment_on',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost'),
            preserve_default=False,
        ),
    ]
