# Generated by Django 5.0.3 on 2024-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_commentmodelform_comment_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodelform',
            name='comment_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
