# Generated by Django 5.0.3 on 2024-04-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_commentmodelform_comment_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodelform',
            name='comment_by',
        ),
    ]
