# Generated by Django 5.0.3 on 2024-04-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_commentmodel_delete_commentmodelform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blogs.blogpost'),
        ),
    ]
